version: '2'

services:

  app:
    build: 
      context: .
      dockerfile: ./build/Dockerfile
    depends_on:
      - db
    ports:
     - "5000:5000"
    volumes:
     - ./src:/src

  db:
    image: mongo:3.4